# 慧签自动生成: 默认音频设备 -> 蓝牙音箱 XFW-M18 (84:C6:22:F6:BF:90)
defaults.bluealsa.device "84:C6:22:F6:BF:90"
defaults.bluealsa.profile "a2dp"
pcm.!default {
    type plug
    slave.pcm {
        type bluealsa
        device "84:C6:22:F6:BF:90"
        profile "a2dp"
    }
    hint {
        show on
        description "HuiQian Bluetooth Speaker (XFW-M18)"
    }
}
ctl.!default {
    type bluealsa
    device "84:C6:22:F6:BF:90"
}