# 慧签 voice.py 专用: 强制 ALSA 默认输出 -> 蓝牙音箱 XFW-M18
pcm.!default {
    type plug
    slave.pcm {
        type bluealsa
        device "84:C6:22:F6:BF:90"
        profile "a2dp"
    }
}
ctl.!default {
    type bluealsa
    device "84:C6:22:F6:BF:90"
}